echo "----- replace test files -----"
./../ex04 txt/test_normal.txt "old" "new"
./../ex04 txt/test_no_s1.txt "" "new"
./../ex04 txt/test_no_s2.txt "old" ""
./../ex04 txt/test_no_both.txt "" ""
./../ex04 txt/test_s1_in_s2.txt "old" "older"
./../ex04 txt/test_s2_in_s1.txt "old" "o"
./../ex04 txt/test_nl.txt "old" "new"
echo "----- finished replace -----"
echo "----- it should return error -----"
./../ex04 txt/test_not_exist.txt "old" "new"
